name: Build Debian Package
run-name: ${{ github.actor }} is building MongoDB debian package
on: [push]
jobs:
  build-dpkg:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Build Tools
        run: sudo apt install -y build-essential lld gdb libcurl4-openssl-dev liblzma-dev python-dev-is-python3 libssl-dev
      - name: Build MongoDB
        run: |
          python3 -m venv .venv --prompt mongo
          source .venv/bin/activate
          python3 -m pip install 'poetry==1.5.1'
          export PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring
          python3 -m poetry install --no-root --sync
          CCFLAGS=-march=native python3 buildscripts/scons.py MONGO_VERSION=0.0.0 tar-all
      - name: Set Up Upterm Session
        uses: lhotari/action-upterm@v1
