name: Build Debian Package
run-name: ${{ github.actor }} is building MongoDB debian package
on: [push]
jobs:
  build-dpkg:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Build Tools
        run: sudo apt install -y build-essential lld gdb libcurl4-openssl-dev liblzma-dev python-dev-is-python3 libssl-dev
      - name: Patch Sources
        run: |
          patch SConstruct << 'EOF'
          @@ -3068,7 +3068,7 @@
            env.Append(
              CCFLAGS=[
                "-fasynchronous-unwind-tables",
          -               "-g2" if not env.TargetOSIs('emscripten') else "-g",
          +               "-g0" if not env.TargetOSIs('emscripten') else "-g",
                "-Wall",
                "-Wsign-compare",
                "-Wno-unknown-pragmas",
          EOF
      - name: Build MongoDB
        run: |
          python3 -m venv .venv --prompt mongo
          source .venv/bin/activate
          python3 -m pip install 'poetry==1.5.1' distlib
          export PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring
          python3 -m poetry install --no-root --sync
          python3 buildscripts/scons.py \
            MONGO_VERSION=7.0.1 \
            MONGO_DISTARCH=linux \
            MONGO_DISTMOD=ubuntu2204 \
            CCFLAGS="-march=native" \
            tar-servers
      - name: Set Up Upterm Session
        uses: lhotari/action-upterm@v1
