name: Build MongoDB Debian Packages
run-name: ${{ github.actor }} is building MongoDB dpkgs
on:
  workflow_dispatch:
    inputs:
      refToBuild:
        description: 'Branch, tag or commit hash to build'
        required: true
        type: string
jobs:
  build-dist:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.refToBuild }}
      - name: Install Build Tools
        run: sudo apt install -y build-essential lld gdb libcurl4-openssl-dev liblzma-dev python-dev-is-python3 libssl-dev
      - name: Patch Sources (disable debug info generation)
        run: |
          patch SConstruct << 'EOF'
          @@ -3068,7 +3068,7 @@
               env.Append(
                   CCFLAGS=[
                       "-fasynchronous-unwind-tables",
          -            "-g2" if not env.TargetOSIs('emscripten') else "-g",
          +            "-g0" if not env.TargetOSIs('emscripten') else "-g",
                       "-Wall",
                       "-Wsign-compare",
                       "-Wno-unknown-pragmas",
          EOF
      - name: Build MongoDB Dist Tarball
        run: |
          python3 -m venv .venv --prompt mongo
          source ./.venv/bin/activate
          python3 -m pip install 'poetry==1.5.1' distlib
          export PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring
          python3 -m poetry install --no-root --sync
          python3 ./buildscripts/scons.py \
            MONGO_DISTARCH=linux \
            MONGO_DISTMOD=ubuntu2204 \
            CCFLAGS="-mno-avx" \
            -j4 --legacy-tarball=true tar-dist
      - name: Collect Binaries
        uses: actions/upload-artifact@v4
          name: binaries
          path: build/opt/pkgs/*
      - name: Create Debian Packages
        run: |
          sudo apt install dpkg-dev rpm debhelper fakeroot
          mkdir ./build_deb
          (cd ./buildscripts && python3 ./packager.py \
            -s `git describe --tags | sed 's/^[^0-9]*//'` \
            -r 1 \
            -a `arch` \
            -t ../build/opt/pkgs/mongodb-dist.tgz \
            -p ../build_deb)
      - name: Collect Artifacts
        uses: actions/upload-artifact@v4
        with:
            name: dist-tarball
            path: build/opt/pkgs/*
